#!/usr/bin/env bash
# Render the Homebrew formula for one release. Called by .github/workflows/release.yml;
# runnable locally to eyeball the output:
#   packaging/homebrew/render-formula.sh 0.1.42 <dir-with-.tar.gz.sha256-files>
set -euo pipefail
version="$1"
shadir="$2"
repo="${GITHUB_REPOSITORY:-rdmontgomery/eigenform}"
base="https://github.com/$repo/releases/download/v$version"

sha() { cut -d' ' -f1 "$shadir/eigenform-$1.tar.gz.sha256"; }

cat <<RUBY
# Generated by eigenform's release workflow — edits here are overwritten each release.
class Eigenform < Formula
  desc "Control surface over Claude Code sessions"
  homepage "https://github.com/$repo"
  version "$version"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "$base/eigenform-aarch64-apple-darwin.tar.gz"
      sha256 "$(sha aarch64-apple-darwin)"
    end
    on_intel do
      url "$base/eigenform-x86_64-apple-darwin.tar.gz"
      sha256 "$(sha x86_64-apple-darwin)"
    end
  end

  on_linux do
    on_intel do
      url "$base/eigenform-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "$(sha x86_64-unknown-linux-gnu)"
    end
  end

  def install
    bin.install "eigenform"
    bin.install_symlink "eigenform" => "ef"
  end

  def caveats
    <<~EOS
      An already-running daemon keeps serving the old version after an upgrade.
      \`ef\` prints a note when that happens; \`ef stop && ef\` switches over
      (this ends open sessions).
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/eigenform --version")
  end
end
RUBY
